### ISSUE TITLE
Support Internet explorer 9+

### ISSUE THREAD

**Issue by paladox** [brion/ogv.js#436] opened 2016-09-24 11:41 UTC
Hi please could you support Internet Explorer 9+ since ie9 is more modern then Internet Explorer 8 and a few users might be using that browser.

**Comment by paladox** [comment] 2016-09-24 11:43
Internet Explorer 10 seems not to work too.

**Comment by brion** [comment] 2016-09-24 17:29
IE 9 cannot be supported due to missing TypedArray support. IE 10 should work fine, unless it recently regressed.

**Comment by brion** [comment] 2016-09-24 17:33
IE 10 seems to have regressed in the file streaming (XMLHttpRequest is missing overrideMimeType for 'binary string' load, but I disabled the IE 10/11/Edge-specific MSStream mode due to reliability issues). Might be able to turn it back on for IE 10.

**Comment by brion** [comment] 2016-09-24 17:41
ie 10 fixed in 8e8a0db (for 1.2.1)
ie 9 cannot be supported.

Closing. :D

**Closed by brion** 2016-09-24 17:41 UTC

**Comment by paladox** [comment] 2016-09-24 17:57
Thanks :)

**Comment by paladox** [comment] 2016-09-24 18:02
@brion hi, could we use https://github.com/substack/typedarray for Internet Explorer 9 support? its a typedarray shim.

**Comment by paladox** [comment] 2016-09-24 18:12
Or we can use core-js https://github.com/zloirock/core-js#ecmascript-6-typed-arrays

**Comment by brion** [comment] 2016-09-24 18:37
No, that would perform very poorly if it worked at all.

**Comment by paladox** [comment] 2016-09-24 18:38
Oh, I tried the type array polyfill and it shows the play button.

**Comment by paladox** [comment] 2016-09-24 18:50
@brion hi, with your patch applied, ie10 still doesn't work.

Shows this error

SEC7120: Origin https://en.random-wikisaur.tk not found in Access-Control-Allow-Origin header.

SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.

VIDEOJS: ERROR: {"description":"Internal XMLHttpRequest Error"} {"headers":{},"statusCode":0}

**Comment by brion** [comment] 2016-09-24 23:54
I can't reproduce your problem with ie10; it's working fine for me at the main demo site pulling files from Commons.
