### ISSUE TITLE
OGV.js always defaults to ogg when trying to play via a blob.

### ISSUE THREAD

**Issue by thedracle** [brion/ogv.js#483] opened 2017-12-05 22:37 UTC
I am attempting to do something fairly standard for video/players these days, which is to load a blob into JS memory, and create an object URL from it, and then play from that url:

```
let myBlob = new Blob(myArrayOfWebM, {type: "video/webm"});

let player = new OGVPlayer();
// Append player to DOM
player.src = URL.createObjectURL(myBlob);
player.play();
```

Unfortunately the loadCodec function in OGVPlayer.js on line 1743 defaults to OGG when given a blob url since it doesn't have 'webm' in it:

```
       function loadCodec(callback) {
                // @todo use the demuxer and codec interfaces directly

                // @todo fix detection proper
                if (currentSrc.match(/\.webm$/i)) {
                        codecOptions.type = 'video/webm';
                } else {
                        codecOptions.type = 'video/ogg';
                }

                codecClass = OGVWrapperCodec;
                callback();
        }
```

It would be very useful to perhaps instead allow an options parameter and set the 'type' to what the player was constructed with. I've tried a dizzying array of things to attempt to override the above behavior, but seem to be running into a dead end at every corner.

Any help or suggestions would be greatly appreciated.

Just a possible idea unless I am missing something obvious: https://github.com/brion/ogv.js/pull/484

**Comment by brion** [comment] 2017-12-05 23:00
It should be possible to get the mime type out of the StreamFile interface (I might have to add something to it), in which case making sure the blob is created with the right type string should do the job. But that's not quite done yet. :) Putting on the todo...

**Comment by brion** [comment] 2017-12-05 23:30
https://github.com/brion/ogv.js/commit/edcfc9a8f36368a59563da56fb9dafa568f724a9 should fix this but I haven't tested with actual blobs. Can you test with the 1.5.1 build when it finishes up?

**Comment by brion** [comment] 2017-12-05 23:53
Unfortunately I'm having some compat issues with that fix, stand by. :)

**Comment by brion** [comment] 2017-12-06 00:03
Ok 1.5.1 going up now.

**Comment by thedracle** [comment] 2017-12-06 00:04
I'll pull down 1.5.1 and test with it as soon as it's up.

I've applied a temporary patch and I can get the blob playing now to 1.5.0, which is great progress.

However, it's short circuiting upon hitting:

```
[Log] [14839.3ms] demuxer ran out of data (on-demand.bundle.js, line 198626)
[Log] [14839.3ms] demuxer loading more data (on-demand.bundle.js, line 198626)
[Log] [14904.2ms] fireEvent framecallback (on-demand.bundle.js, line 198626)
[Log] [14904.3ms] fireEvent timeupdate (on-demand.bundle.js, line 198626)
```

And eventually after it hits:
```
[Log] [15697.6ms] onbufferlow (on-demand.bundle.js, line 198626)
[Log] [15883.1ms] onbufferlow (on-demand.bundle.js, line 198626)
[Log] [16068.7ms] onbufferlow (on-demand.bundle.js, line 198626)
[Log] [16254.5ms] onbufferlow (on-demand.bundle.js, line 198626)
[Log] [16440.2ms] onbufferlow (on-demand.bundle.js, line 198626)
[Log] [16626.1ms] onbufferlow (on-demand.bundle.js, line 198626)
[Log] [16811.8ms] onstarved: halting audio due to starvation (on-demand.bundle.js, line 198626)
[Log] [16811.8ms] pausing at 15.975328798185956 (on-demand.bundle.js, line 198626)
```

Basically it plays a couple seconds just fine, and then locks up.

If I download the blob to disk, and server it using a webserver, and set the .src to the link on the server it plays back fine.

Maybe something to do with reading the blob too fast? There are probably a lot of differences here, and this doesn't seem to be a normal use case for you.

**Comment by brion** [comment] 2017-12-06 00:11
If I had to guess, there's some difficulties with loading the data chunks out of the blob URL; the current code is oriented at loading chunks of an HTTP file with partial data ranges, which might be flakier with Blobs since they're not real HTTP. I'd like to iron out any issues there, since it ought to "just work"... I'll do some more tests later and see if I can reproduce it in controlled circumstances.

Do you have a sample file I can test with, or rough characteristics I can try to duplicate (size/resolution/codec)?

**Comment by thedracle** [comment] 2017-12-06 00:36
So the following recording I just took will reproduce it:

https://s3-us-west-1.amazonaws.com/projectdrop/repro.webm

**Comment by thedracle** [comment] 2017-12-06 18:16
Hi Brion--- testing with 1.5.1, I'm not sure if there is any way to specify the content-type header via a Blob:

```
let myBlob = new Blob(myArrayOfWebM, {type: "video/webm"});
```

or

```
let myBlob = new Blob(myArrayOfWebM, {'content-type': "video/webm"});
```

Don't seem to do it.

Neither does specifying 'type' in the options provided to OGVPlayer.

I'm not sure if just from a blob URL it is possible to specify these headers.

**Comment by thedracle** [comment] 2017-12-06 19:13
So- it seems like the buffering issue I detailed above is something to do with the 'stream' module, and specifically the BinaryStringBackend that is getting selected.

It ends up reading only a portion of the blob via its onXHRProgress callback, and delivering it to the cache, and never delivers any future slices. 

It always seems to be around a 1MB chunk, and so the cache actually ends up running out of data.

I added logs at backend/binary-string-backend.js:

```
  onXHRProgress() {
    const slice = this.xhr.responseText.slice(this.bytesRead);
    if (slice.length > 0) {
      this.bytesRead += slice.length;
      this.emit('buffer', slice);
    }
``` 

And at line 151 of stream-file.js:
```
 } else {
              backend.on('buffer', (buffer) => {
                if (backend === this._backend) {
                  this._cache.write(buffer);
                }
              });
```

So, for a recording of the size 1419592, I see logged:
[Log] DOWNLOADED SLICE: 1048576 (on-demand.bundle.js, line 205169)
[Log] WRITING BUFFER TO CACHE: 1048576 (on-demand.bundle.js, line 203568)

And this is basically the final amount of data that is available to ogv.js indefinitely.

I wonder if perhaps it's possible for me to use a different backend, or if there is something wrong in my browser (Safari 11) that is causing the XMLHttpRequest to the blob url not provide all of the data.

Thanks so much for your help so far and making this awesome project.

**Comment by thedracle** [comment] 2017-12-06 19:55
I'm going to move comments on the streaming issue to stream-file.

**Comment by thedracle** [comment] 2017-12-06 20:03
Hi Brion--- testing with 1.5.1, I'm not sure if there is any way to specify the content-type header via a Blob:

let myBlob = new Blob(myArrayOfWebM, {type: "video/webm"});
or

let myBlob = new Blob(myArrayOfWebM, {'content-type': "video/webm"});
Don't seem to do it.

Neither does specifying 'type' in the options provided to OGVPlayer.

I'm not sure if just from a blob URL it is possible to specify these headers.

**Comment by brion** [comment] 2017-12-06 20:45
Yeah, that may be from the override of the type in the reading... I'll do more testing tonight or tomorrow and see what's going on in there.

**Comment by brion** [comment] 2017-12-09 07:56
Ok, with on https://github.com/brion/stream-file/issues/9 the other blob issues are resolved in Safari -- but still have to work around the type detection. At this point I'm recommending just checking magic bytes at the start of the file, it's foolproof enough for Ogg vs WebM.

**Closed** 2017-12-09 20:57 UTC
