### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by Marc477** [brion/ogv.js#313] opened 2015-09-23 03:13 UTC
I cant make it work in Safari (tried windows and iphone). Everything is fine in firefox and chrome
 
Strangely i get an error: Refused to get unsafe header "Content-Range"
Even if "access-control-expose-headers: Accept-Ranges, Content-Type, Content-Length, Content-Range" is set

I also get 
ReferenceError: Can't find variable: console
and
TypeError: 'null' is not an object (evaluating 'stream.readBytes')

**Comment by Marc477** [comment] 2015-09-23 03:26
Ok maybe its Safari windows that doesnt support access-control-expose-headers, because I tried your demo and it is working on the iphone, but not on safari windows.

So it is something else on iphone. Hard to debug..

**Comment by brion** [comment] 2015-09-23 03:28
I think Safari for Windows last version is 5.something which won't work as its missing various features.

**Comment by Marc477** [comment] 2015-09-23 03:39
Well I doesnt really matter if it doesnt work on Safari windows.. But I want to make it work on Iphone and I tought the bug was related to the one on Safari windows...

This is not working on my iphone 4S
     var link1 =       "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1a/%C2%BFQu%C3%A9_es_Wikipe    dia%3F.ogv/%C2%BFQu%C3%A9_es_Wikipedia%3F.ogv.160p.ogv";
            
            var player = new OGVPlayer();
            
            var container = document.getElementById('vframe');
			container.appendChild(player);
            
            player.src = link1;
            player.play();

Also, your demo has no sound on my iphone

**Comment by Marc477** [comment] 2015-09-23 14:43
Ok I think I found the bug: for some reason on iphone when you use  player.play(); just after creating the player (or even in a setTimeout), something crashes and you cant run play() after that. If I remove the player.play(). Then I can start the player with a button.

Working: http://madesbiens.ca/DemoOGV.html
not woking on iphone: http://madesbiens.ca/DemoOGV-bad.html

**Comment by Mikushi** [comment] 2015-09-23 15:06
@Marc477 That's not a bug though, you cannot autoplay or programmatically trigger the play() on iOS due to restriction on the AudioContext in Safari which must be instantiated from a user interaction event (touch is the only valid one on iOS9).

**Comment by Marc477** [comment] 2015-09-23 15:32
Ohh thats why, I knew it for the video element, but since the whole point of ogv.js is to avoid the video element (and therefore enable autoplay on iphones), I tought it would work..

But the problem is not that it only doesnt start, it crashes the program because after it is impossible to use player.play() in a click:

See exemple here:
http://madesbiens.ca/DemoOGV-weird.html

You can only start the player between the loadedmetadata and play event (you have 4 secs). After that it is too late (crashed)

**Comment by brion** [comment] 2015-09-23 16:19
I believe it ends up in an inconsistent state in this case as it expects to be activated only when valid. :)

**Comment by brion** [comment] 2015-09-30 19:34
Ok I'm going to merge this in with the general audio/autostart bug...

**Comment by brion** [comment] 2015-09-30 19:34
merged underlying audio/autostart ios bug  to https://github.com/brion/ogv.js/issues/313

**Comment by brion** [comment] 2015-09-30 19:35
or rather to https://github.com/brion/ogv.js/issues/112 pastefail :D

**Closed by brion** 2015-09-30 19:34 UTC
