### ISSUE TITLE
Safari/iphone

### ISSUE THREAD

**Issue by Bengals3381** [brion/ogv.js#324] opened 2015-12-18 17:25 UTC
Hey Brian, I'm having a little trouble playing my player/video in safari on the iphone. I even added a play button because I know that the ogv video doesn't automatically play on the iphone. I t works well in safari on my Mac, BUT i can't seem to figure it out on the iphone. Could you help out with this please..

**Comment by Bengals3381** [comment] 2016-01-10 21:11
Brian I am still struggling with this, I can't seem to get this to play on the iphone. Can you help me please this is work related.

**Comment by LimeStreem** [comment] 2016-01-17 16:35
It seems I'm struggling with same problem of @Bengals3381 .

I don't know this information can be helpful for contributors or users to solve this problem. 
But, In my case I tried to update canvas with a video source like this.

```javascript
var player = new OGVPlayer({
    enableWebM: false,
    webGL: false,
    canvas: canvas
  });

  player.src = '/Something.ogv';
  player.play();
```

Then, I wrote following code to use loaded texture with three.js.

```
const texture = new THREE.Texture(canvas);
texture.needsUpdate = true;
```

**Problem**

Safari on iPhone produce a warning "THREE.WebGLRenderer: S3TC compressed textures not supported.". And the texture was initialized with white color.

**Consideration**

This was caused by lack of compatibility for WEBGL_compressed_texture_s3tc/(https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc/) in iPhone.

However, when I tried to load video from WebM file, it appeared just a static image.
I guess this means when decoding codecs and pass into canvas, this library uses s3tc compression for .ogv files and standard img structure for webM files.

Therefore, If it is possible not to use s3tc compression for passing into canvas, it solve this problem hopefully.

**Comment by brion** [comment] 2016-04-09 10:19
Ogv.js does not compress any textures... No idea what that three.js error means.

**Comment by brion** [comment] 2016-04-09 10:20
@Bengals3381 are you still having trouble? Can you point to your example page to test?

**Comment by brion** [comment] 2017-04-20 07:27
(closing out old entries)

**Closed by brion** 2017-04-20 07:27 UTC
